/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
import { JSX } from '@stencil/core';


export namespace Components {
  interface MyApp {}
}

declare namespace LocalJSX {
  interface MyApp extends JSXBase.HTMLAttributes {}

  interface ElementInterfaces {
    'MyApp': Components.MyApp;
  }

  interface IntrinsicElements {
    'MyApp': LocalJSX.MyApp;
  }
}
export { LocalJSX as JSX };

declare module "@stencil/core" {
  export namespace JSX {
    interface ElementInterfaces extends LocalJSX.ElementInterfaces {}
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}

declare global {


  interface HTMLMyAppElement extends Components.MyApp, HTMLStencilElement {}
  var HTMLMyAppElement: {
    prototype: HTMLMyAppElement;
    new (): HTMLMyAppElement;
  };
  interface HTMLElementTagNameMap {
    'my-app': HTMLMyAppElement
  }

  interface ElementTagNameMap {
    'my-app': HTMLMyAppElement;
  }
}

